name: Website Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Build docs
        env:
          DOCS_BASEURL: "https://acoular.org/"
        run: uv run make -C docs html

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: build-docs
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v7
        with:
          name: build-docs
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          keep_files: true
          cname: acoular.org
          enable_jekyll: false
